use datawarehouse;
go

select * from INFORMATION_SCHEMA.TABLES;

select * from INFORMATION_SCHEMA.COLUMNS
where TABLE_NAME = 'dim_product';

select * from gold.dim_customer;

--Find the date of first and last order

select * from gold.fact_sales;

select 
MIN(order_date) first_order,
MAX(order_date) last_order,
DATEDIFF(year, MIN(order_date), MAX(order_date)) order_range_years
from gold.fact_sales;

--Find the youngest and oldest customer

select 
MIN(birthdate) oldest_customer,
MAX(birthdate) younest_customer,
DATEDIFF(year, MIN(birthdate), GETDATE()),
DATEDIFF(year, MAX(birthdate), GETDATE())
from gold.dim_customer;

-- Find the total sales 

select 
SUM(sales) as total_sales
from gold.fact_sales

-- Find how many items are sold

select 
SUM(quantity) AS total_quantity
from gold.fact_sales;

-- Find the average selling price

select 
AVG(sales) AS avg_sales
from gold.fact_sales;

-- Total the number of order 

select 
COUNT(distinct order_number)
from gold.fact_sales;

-- Total the total number of products 

select 
COUNT(distinct product_name)
from gold.dim_product;

-- Find the total number of customers

select 
count(distinct customer_id)
from gold.dim_customer;

-- Find the total number of customers who have placed an order

select 
count(distinct d.customer_key)
from gold.fact_sales f
left join gold.dim_customer d
on f.customer_key = d.customer_key

/*
Generate key metrics for reporting 
*/
select 
'Total Sales' metrics_for_report,
SUM(sales) as total_sales
from gold.fact_sales

union all

select 
'Total Quantity',
SUM(quantity) total_quantity
from gold.fact_sales

union all

select
'Average Sales',
AVG(sales) as avg_sales
from gold.fact_sales

union all

select 
'Total orders',
COUNT(distinct order_number)
from gold.fact_sales

union all

select 
'Total Product',
COUNT(distinct product_name)
from gold.dim_product;

---------------------------------------------------------------------------------------------------
---------------------------------------------------------------------------------------------------

-- Find total number of customers by country

select COUNT(customer_number), country from gold.dim_customer
group by country
order by 1,2

-- Find total customers by gender

select gender, COUNT(customer_number) from gold.dim_customer
group by gender
order by 1,2

-- Find total products by category 

select category, count(product_name) from gold.dim_product
group by category

-- Find the average cost of each category

select d.category, AVG(f.price)
from gold.fact_sales f
left join gold.dim_product d
on f.product_key = d.product_key
group by d.category

-- What is the total revenue generated for each category

select d.category, sum(f.sales)
from gold.fact_sales f
left join gold.dim_product d
on f.product_key = d.product_key
group by d.category

-- Find the total revenue generated by each customer

select d.customer_id, sum(f.sales)
from gold.fact_sales f
left join gold.dim_customer d
on f.product_key = d.customer_key
group by d.customer_id

-- What is the distribution of sold items across countries

select c.country, d.category, count(d.product_key) total_count
from gold.fact_sales f
left join gold.dim_product d
on f.product_key = d.product_key
left join gold.dim_customer c
on f.customer_key = c.customer_key
group by d.category, c.country
order by c.country asc, total_count desc

-- Which 5 products generate the highest revenue

select top 5 with ties
d.product_name, 
SUM(f.sales) as total_sales_product 
from gold.fact_sales f
left join gold.dim_product d
on f.product_key = d.product_key
group by d.product_name
order by 1,2

-- What are the 5 worst-performing products 

select top 5 with ties
d.product_name, 
SUM(f.sales) as total_sales_product 
from gold.fact_sales f
left join gold.dim_product d
on f.product_key = d.product_key
group by d.product_name
order by total_sales_product

-- Find top 10 customers who generate the highest revenue 

select top 10 with ties
d.customer_id, d.first_name, SUM(f.sales) high_sales 
from gold.fact_sales f
left join gold.dim_customer d
on f.customer_key = d.customer_key
group by d.customer_id, d.first_name
order by high_sales desc

-- The 3 customers with the fewest sales placed 

select top 3 with ties
d.customer_id, d.first_name, SUM(f.sales) lower_revenue 
from gold.fact_sales f
left join gold.dim_customer d
on f.customer_key = d.customer_key
group by d.customer_id, d.first_name
order by lower_revenue

-- The 3 customers with the fewest orders placed 

select top 3 with ties
d.customer_key, d.first_name, d.last_name, 
count(distinct f.order_number) lower_revenue 
from gold.fact_sales f
left join gold.dim_customer d
on f.customer_key = d.customer_key
group by d.customer_key, d.first_name, d.last_name
order by lower_revenue

select * from gold.fact_sales
